# Generated by Django 4.1.6 on 2023-02-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb200',
            field=models.ImageField(blank=True, upload_to='images/thumbnails200/'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumb400',
            field=models.ImageField(blank=True, upload_to='images/thumbnails400/'),
        ),
    ]
