# Generated by Django 4.1.6 on 2023-02-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_create_date_link_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='base.image'),
        ),
    ]
