# Generated by Django 4.1.6 on 2023-02-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_link_options_alter_link_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='image',
            name='binary',
            field=models.ImageField(blank=True, upload_to='images/binary/'),
        ),
    ]
