# Generated by Django 4.1.6 on 2023-02-14 01:22

import base.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_link_options_alter_link_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='links',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tier',
            name='original',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[base.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='link',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='CustomThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/customs/')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs', to='base.tier')),
            ],
        ),
    ]
