# Generated by Django 4.1.6 on 2023-02-14 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_customsize_delete_customthumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/customs/')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs', to='base.image')),
            ],
        ),
    ]
