# Generated by Django 4.1.6 on 2023-02-14 23:45

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_customthumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='thumb200',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tier',
            name='thumb400',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', validators=[base.models.validate_image]),
        ),
    ]
